---
name: 'Setup Mint'
description: 'This action sets up a Mint programming language.'
branding:
  icon: feather
  color: green
inputs:
  version:
    description: 'Mint version.'
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'
