name: CI (latest)

on: push

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          ref: v1.0.0
      - uses: Adzz/jest_test_action@v1.0.0
        # env:
        #   SRC_PATH: ${{ github.workspace }}
        with:
          package-manager: npm
          command: test
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        version: ['0.7.1','0.8.0','0.9.0']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          ref: v1.0.0
      - uses: fabasoad/setup-mint-action@v1.0.0
        with:
          version: ${{ matrix.version }}
      - name: Run script
        run: mint init project-${{ matrix.os }}
