name: Mint (master)

on: push

jobs:
  setup:
    name: Setup
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          version: '0.8.0'
      - name: Run script
        run: mint init project-${{ matrix.os }}
